# Generated by Django 5.2.1 on 2025-05-09 18:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendance_date',
            field=models.DateField(default=django.utils.timezone.localdate, editable=False),
        ),
    ]
