# Generated by Django 5.2.1 on 2025-05-11 11:59

import django.db.models.deletion
import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_attendance_attendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(default=students.models.first_day_of_current_month, verbose_name='شهر الدفع')),
                ('paid_on', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ووقت الدفع')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='students.students', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
                'ordering': ['-month'],
                'constraints': [models.UniqueConstraint(fields=('student', 'month'), name='unique_payment_per_month')],
            },
        ),
    ]
