# Generated by Django 5.2.1 on 2025-05-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'حضور', 'verbose_name_plural': 'الحضور'},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'verbose_name': 'طالب', 'verbose_name_plural': 'الطلاب'},
        ),
        migrations.AddField(
            model_name='students',
            name='free_tries',
            field=models.PositiveSmallIntegerField(default=3, verbose_name='عدد الفرص المجانية المتبقية'),
        ),
        migrations.AddField(
            model_name='students',
            name='last_reset_month',
            field=models.DateField(blank=True, help_text='يُحدَّث فقط عند الدفع', null=True, verbose_name='آخر شهر إعادة تعيين'),
        ),
    ]
