# Generated by Django 5.2.1 on 2025-05-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_attendance_options_alter_students_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_absent',
            field=models.BooleanField(default=False, verbose_name='غياب'),
        ),
    ]
