# Generated by Django 5.2.1 on 2025-05-21 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_attendance_is_absent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Basics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_time', models.TimeField(verbose_name='آخر وقت')),
                ('month_price', models.IntegerField(verbose_name='سعر الشهر')),
                ('logo', models.ImageField(upload_to='logo/', verbose_name='شعار')),
            ],
            options={
                'verbose_name': 'أساسيات',
                'verbose_name_plural': 'الأساسيات',
            },
        ),
    ]
