# Generated by Django 5.2.1 on 2025-05-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_basics'),
    ]

    operations = [
        migrations.AddField(
            model_name='basics',
            name='free_tries',
            field=models.PositiveSmallIntegerField(default=3, help_text='عدد الفرص المجانية المتاحة للطلاب', verbose_name='عدد الفرص المجانية'),
        ),
    ]
