# Generated by Django 4.2.21 on 2025-05-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_basics_free_tries'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'attendance_date'], name='students_at_student_ade56e_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['attendance_date'], name='students_at_attenda_e4bf21_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'is_absent', 'attendance_date'], name='students_at_student_8a3479_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'month'], name='students_pa_student_d609bf_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['month'], name='students_pa_month_4a690d_idx'),
        ),
    ]
