# Generated by Django 5.2.1 on 2025-05-27 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_notificationcategory_attendance_arrival_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basics',
            name='last_time',
        ),
        migrations.AddField(
            model_name='basics',
            name='ate_arrival_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت اعتبار التأخير'),
        ),
    ]
