# Generated by Django 5.2.1 on 2025-06-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_students_has_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='branch',
            field=models.CharField(choices=[('branch_a', 'الفرع أ'), ('branch_b', 'الفرع ب'), ('unknown', 'غير معروف')], default='unknown', max_length=50, verbose_name='الفرع'),
        ),
    ]
