# Generated by Django 5.2.1 on 2025-06-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_students_has_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='basics',
            name='default_term_duration_months',
            field=models.PositiveSmallIntegerField(blank=True, default=4, null=True, verbose_name='المدة الافتراضية للفصل (بالأشهر)'),
        ),
        migrations.AddField(
            model_name='basics',
            name='term_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='سعر الترم'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('monthly', 'شهري'), ('term', 'ترم')], default='monthly', max_length=10, verbose_name='نوع الدفع'),
        ),
        migrations.AddField(
            model_name='payment',
            name='term_duration_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text='يستخدم فقط إذا كان نوع الدفع فصلي', null=True, verbose_name='مدة الفصل (بالأشهر)'),
        ),
        migrations.AddField(
            model_name='students',
            name='branch',
            field=models.CharField(choices=[('branch_a', 'الاساسي'), ('branch_b', 'البحري'), ('unknown', 'غير معروف')], default='unknown', max_length=50, verbose_name='الفرع'),
        ),
        migrations.DeleteModel(
            name='BroadcastMessage',
        ),
        migrations.DeleteModel(
            name='NotificationCategory',
        ),
    ]
