# Generated by Django 5.2.1 on 2025-06-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_basics_default_term_duration_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basics',
            name='current_branch',
            field=models.CharField(choices=[('branch_a', 'الاساسي'), ('branch_b', 'البحري'), ('unknown', 'غير معروف')], default='unknown', max_length=50, verbose_name='الفرع الحالي للنظام'),
        ),
    ]
