# Generated by Django 5.2.1 on 2025-06-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_students_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='basics',
            name='default_term_duration_months',
            field=models.PositiveSmallIntegerField(blank=True, default=3, null=True, verbose_name='المدة الافتراضية للفصل (بالأشهر)'),
        ),
        migrations.AddField(
            model_name='basics',
            name='term_price',
            field=models.IntegerField(blank=True, null=True, verbose_name='سعر الفصل'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('monthly', 'شهري'), ('term', 'فصلي')], default='monthly', max_length=10, verbose_name='نوع الدفع'),
        ),
        migrations.AddField(
            model_name='payment',
            name='term_duration_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text='يستخدم فقط إذا كان نوع الدفع فصلي', null=True, verbose_name='مدة الفصل (بالأشهر)'),
        ),
    ]
