# Generated by Django 5.2.1 on 2025-06-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_basics_current_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basics',
            name='current_branch',
            field=models.CharField(choices=[('branch_a', 'الاساسي'), ('branch_b', 'البحري'), ('unknown', 'غير معروف')], default='unknown', max_length=50, verbose_name='الفرع'),
        ),
    ]
