# Generated by Django 5.2.1 on 2025-06-18 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_alter_basics_current_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basics',
            old_name='current_branch',
            new_name='branch',
        ),
    ]
