# Generated by Django 5.2.1 on 2025-06-18 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0016_rename_current_branch_basics_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basics',
            old_name='branch',
            new_name='current_branch',
        ),
    ]
