# Generated by Django 5.2.1 on 2025-06-21 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_rename_branch_basics_current_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='branch',
            new_name='current_branch',
        ),
    ]
